import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import UserContextProvider from "@/context/User/UserContextProvider";
import ProjectContextProvider from "@/context/Project/ProjectContextProvider";
import IssueContextProvider from "@/context/Issue/IssueContextProvider";
import ActivityContextProvider from "@/context/Activity/ActivityContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserContextProvider>
            <ProjectContextProvider>
              <IssueContextProvider>
                <ActivityContextProvider>
                  <div className=" flex min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white">
                    {children}
                  </div>
                </ActivityContextProvider>
              </IssueContextProvider>
            </ProjectContextProvider>
          </UserContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
